// Generated by Home Manager.



user_pref("app.shield.optoutstudies.enabled", false);
user_pref("browser.discovery.enabled", false);
user_pref("browser.download.dir", "/home/gin/Downloads");
user_pref("browser.download.folderList", 2);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.safebrowsing.downloads.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.block_dangerous", false);
user_pref("browser.safebrowsing.downloads.remote.block_dangerous_host", false);
user_pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);
user_pref("browser.safebrowsing.downloads.remote.block_uncommon", false);
user_pref("browser.safebrowsing.downloads.remote.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.url", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("datareporting.healthreport.service.enabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("experiments.enabled", false);
user_pref("experiments.manifest.uri", "");
user_pref("experiments.supported", false);
user_pref("extensions.shield-recipe-client.enabled", false);
user_pref("font.name.monospace.x-western", "Input Mono");
user_pref("font.name.sans-serif.x-western", "Inter");
user_pref("font.name.serif.x-western", "New York");
user_pref("gfx.webrender.all", true);
user_pref("loop.logDomains", false);
user_pref("media.ffmpeg.vaapi.enabled", true);
user_pref("network.cookie.cookieBehavior", 1);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.unified", false);



