alang=jap,jpn,jp,en,eng
audio-channels=auto-safe
audio-device=auto
audio-pitch-correction=yes
autofit-larger=50%
cache=yes
geometry=50%
hwdec=auto
vo=gpu
keep-open=yes
ontop=yes
osd-bar=no
osd-on-seek=msg
screenshot-directory=/home/gin/Pictures/Screenshots/
screenshot-template=%F-shot%#02n-%p
slang=en,eng
sub-auto=fuzzy
sub-paths=sub:subs:subtiles:Sub:Subs:Subtitles
