"
org.gnome.desktop.wm.keybindings toggle-maximized ['<Super>f']
org.gnome.desktop.wm.preferences num-workspaces 6

org.gnome.desktop.wm.keybindings move-to-workspace-1 ['<Shift><Super>exclam']
org.gnome.desktop.wm.keybindings move-to-workspace-2 ['<Shift><Super>at']
org.gnome.desktop.wm.keybindings move-to-workspace-3 ['<Shift><Super>numbersign']
org.gnome.desktop.wm.keybindings move-to-workspace-4 ['<Shift><Super>dollar']
org.gnome.desktop.wm.keybindings move-to-workspace-5 [<Shift><Super>asciicircum]
org.gnome.desktop.wm.keybindings move-to-workspace-6 [<Shift><Super>percent]
org.gnome.desktop.wm.keybindings move-to-workspace-7 @as []
org.gnome.desktop.wm.keybindings move-to-workspace-8 @as []
org.gnome.desktop.wm.keybindings move-to-workspace-9 @as []
org.gnome.desktop.wm.keybindings move-to-workspace-10 @as []
org.gnome.desktop.wm.keybindings move-to-workspace-11 @as []
org.gnome.desktop.wm.keybindings move-to-workspace-12 @as []

org.gnome.desktop.wm.keybindings switch-to-workspace-1 ['<Super>1']
org.gnome.desktop.wm.keybindings switch-to-workspace-2 ['<Super>2']
org.gnome.desktop.wm.keybindings switch-to-workspace-3 ['<Super>3']
org.gnome.desktop.wm.keybindings switch-to-workspace-4 ['<Super>4']
org.gnome.desktop.wm.keybindings switch-to-workspace-5 ['<Super>5']
org.gnome.desktop.wm.keybindings switch-to-workspace-6 ['<Super>6']
org.gnome.desktop.wm.keybindings switch-to-workspace-7 @as []
org.gnome.desktop.wm.keybindings switch-to-workspace-8 @as []
org.gnome.desktop.wm.keybindings switch-to-workspace-9 @as []
org.gnome.desktop.wm.keybindings switch-to-workspace-10 @as []
org.gnome.desktop.wm.keybindings switch-to-workspace-11 @as []
org.gnome.desktop.wm.keybindings switch-to-workspace-12 @as []
org.gnome.desktop.wm.keybindings switch-to-workspace-last @as []

org.gnome.desktop.wm.keybindings switch-to-workspace-right ['<Super>bracketright']
org.gnome.desktop.wm.keybindings switch-to-workspace-left ['<Super>bracketleft']
org.gnome.desktop.wm.keybindings switch-to-workspace-down @as []
org.gnome.desktop.wm.keybindings switch-to-workspace-up @as []

org.gnome.desktop.wm.keybindings move-to-workspace-up @as []
org.gnome.desktop.wm.keybindings move-to-workspace-last @as []
org.gnome.desktop.wm.keybindings move-to-workspace-right ['<Shift><Super>braceright']
org.gnome.desktop.wm.keybindings move-to-workspace-left ['<Shift><Super>braceleft']
org.gnome.desktop.wm.keybindings move-to-workspace-down @as []

org.gnome.desktop.wm.keybindings cycle-windows-backward ['<Shift><Alt>Escape']
org.gnome.desktop.wm.keybindings cycle-windows ['<Alt>Escape']
org.gnome.desktop.wm.keybindings switch-input-source-backward ['<Shift><Super>space', '<Shift>XF86Keyboard']

org.gnome.desktop.peripherals.touchpad tap-to-click true
org.gnome.desktop.peripherals.keyboard repeat-interval uint32 40
org.gnome.desktop.wm.keybindings switch-input-source ['<Super>space', 'XF86Keyboard']

org.gnome.desktop.sound allow-volume-above-100-percent true

org.gnome.desktop.wm.keybindings move-to-side-n @as []
org.gnome.desktop.wm.keybindings maximize-horizontally @as []
org.gnome.desktop.wm.keybindings activate-window-menu @as []
org.gnome.desktop.wm.keybindings set-spew-mark @as []
org.gnome.desktop.wm.keybindings switch-windows-backward @as []
org.gnome.desktop.wm.keybindings maximize-vertically @as []
org.gnome.desktop.wm.keybindings move-to-corner-sw @as []
org.gnome.desktop.wm.keybindings maximize @as []
org.gnome.desktop.wm.keybindings panel-main-menu @as []
org.gnome.desktop.wm.keybindings close ['<Super>q']
org.gnome.desktop.wm.keybindings move-to-monitor-up @as []
org.gnome.desktop.wm.keybindings raise-or-lower @as []
org.gnome.desktop.wm.keybindings move-to-side-e @as []
org.gnome.desktop.wm.keybindings move-to-monitor-right @as []
org.gnome.desktop.wm.keybindings switch-windows @as []
org.gnome.desktop.wm.keybindings panel-run-dialog @as []
org.gnome.desktop.wm.keybindings switch-panels-backward @as []
org.gnome.desktop.wm.keybindings unmaximize @as []
org.gnome.desktop.wm.keybindings switch-applications @as []
org.gnome.desktop.wm.keybindings move-to-corner-ne @as []
org.gnome.desktop.wm.keybindings move-to-side-s @as []
org.gnome.desktop.wm.keybindings show-desktop @as []
org.gnome.desktop.wm.keybindings move-to-center @as []
org.gnome.desktop.wm.keybindings raise @as []
org.gnome.desktop.wm.keybindings move-to-corner-se @as []
org.gnome.desktop.wm.keybindings toggle-shaded @as []
org.gnome.desktop.wm.keybindings cycle-group-backward @as []
org.gnome.desktop.wm.keybindings cycle-panels-backward @as []
org.gnome.desktop.wm.keybindings move-to-monitor-left @as []
org.gnome.desktop.wm.keybindings switch-applications-backward @as []
org.gnome.desktop.wm.keybindings move-to-monitor-down @as []
org.gnome.desktop.wm.keybindings toggle-fullscreen @as []
org.gnome.desktop.wm.keybindings cycle-group @as []
org.gnome.desktop.wm.keybindings switch-group-backward @as []
org.gnome.desktop.wm.keybindings switch-group @as []
org.gnome.desktop.wm.keybindings begin-resize @as []
org.gnome.desktop.wm.keybindings begin-move @as []
org.gnome.desktop.wm.keybindings move-to-side-w @as []
org.gnome.desktop.wm.keybindings move-to-corner-nw @as []
org.gnome.desktop.wm.keybindings always-on-top @as []
org.gnome.desktop.wm.keybindings cycle-panels @as []
org.gnome.desktop.wm.keybindings lower @as []
org.gnome.desktop.wm.keybindings toggle-above @as []
org.gnome.desktop.wm.keybindings switch-panels @as []
org.gnome.desktop.wm.keybindings minimize @as []
org.gnome.desktop.wm.keybindings toggle-on-all-workspaces @as []

org.gnome.shell.extensions.auto-move-windows application-list ['firefox.desktop:1', 'org.gnome.Lollypop.desktop:4']
org.gnome.shell.keybindings toggle-message-tray ['<Super>grave']

org.gnome.shell.keybindings switch-to-application-1 @as []
org.gnome.shell.keybindings switch-to-application-2 @as []
org.gnome.shell.keybindings switch-to-application-3 @as []
org.gnome.shell.keybindings switch-to-application-4 @as []
org.gnome.shell.keybindings switch-to-application-5 @as []
org.gnome.shell.keybindings switch-to-application-6 @as []
org.gnome.shell.keybindings switch-to-application-7 @as []
org.gnome.shell.keybindings switch-to-application-8 @as []
org.gnome.shell.keybindings switch-to-application-9 @as []
org.gnome.shell.keybindings switch-to-application-10 @as []
org.gnome.shell.keybindings toggle-application-view @as []
org.gnome.shell.keybindings focus-active-notification @as []
org.gnome.shell.keybindings open-application-menu @as []
org.gnome.shell.keybindings toggle-overview @as []
org.gnome.shell.keybindings shift-overview-up @as []
org.gnome.shell.keybindings shift-overview-down @as []
org.gnome.shell.overrides dynamic-workspaces false
"
